baseURL = 'https://www.mersh.com/'
title = 'mersh.com'
copyright = 'The content for this site is published under the <a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a> license.'
languageCode =  'en-us'
contentDir = 'content/'
rssLimit = 20

[author]
    name = 'Garrett Howard'
    email = 'garrett@mersh.com'
    github = 'garhow'
    sudomemo = '5C48A97065F1D04B@DSi'

[params]
    description = 'Programming, games, and more'
    message = "❄ merry christmas! i updated the website to be more festive... i also updated the games section and added some more of my recent projects to the lists. i'm currently documenting my halo 2 playthrough so be sure to check out that page! tot ziens ❄"
    source = 'https://github.com/garhow/website/'
